---
version: "{build}"
clone_depth: 5
init:
  # Remove any ENV settings related to OpenSSL-Win
  - set SSL_CERT_DIR=
  - set SSL_CERT_FILE=
  - set OPENSSL_CONF=
  - set OPENSSL_DIR=
  # Minimize path so bash conflicts don't arise
  - set base_path=C:\ruby24-x64\bin;C:\Program Files\7-Zip;C:\Program Files\AppVeyor\BuildAgent;C:\Program Files\Git\cmd;C:\Windows\system32;C:\Program Files;C:\Windows
  - git clone -q --depth=5 --no-tags --branch=trunk https://github.com/ruby/ruby.git C:\ruby
  - appveyor DownloadFile https://ci.appveyor.com/api/projects/MSP-Greg/ruby-loco/artifacts/ruby_trunk.7z -FileName C:/ruby_trunk.7z
  - 7z x C:/ruby_trunk.7z -oC:/ruby_trunk
  - set PATH=C:/ruby_trunk/bin;%base_path%

on_finish:
- ruby -v
  
build: off

deploy: off
  
  install:
  - cd C:\ruby
  - C:\msys64\usr\bin\patch  -p1 -N --no-backup-if-mismatch -i C:\projects\trunk_mingw_testing\test.patch 

test_script:
  - cd C:\ruby\test
  - ruby -v --disable-gems runner.rb -v -I./lib --show-skip webrick/test_ssl_server.rb
